# Generated by Django 4.2.1 on 2023-06-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name', max_length=50)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('date_created', models.DateTimeField(verbose_name='Date of account creation')),
                ('last_measurement', models.DateTimeField(verbose_name='DateTime of last record')),
                ('last_time_alcohol_consumed', models.DateTimeField(verbose_name='Last alcohol consumption')),
                ('address', models.CharField(default='No address', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RunningAverageDay',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ben12app.client')),
                ('alcohol_level', models.FloatField(default=-1)),
                ('blood_oxygen_level', models.FloatField(default=-1)),
                ('heartrate', models.IntegerField(default=-1)),
                ('num_records', models.IntegerField(default=0)),
                ('date_last_updated', models.DateTimeField(verbose_name='Date of last update')),
            ],
        ),
        migrations.CreateModel(
            name='RunningAverageMonth',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ben12app.client')),
                ('alcohol_level', models.FloatField(default=-1)),
                ('blood_oxygen_level', models.FloatField(default=-1)),
                ('heartrate', models.IntegerField(default=-1)),
                ('num_records', models.IntegerField(default=0)),
                ('date_last_updated', models.DateTimeField(verbose_name='Date of last update')),
            ],
        ),
        migrations.CreateModel(
            name='RunningAverageWeek',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ben12app.client')),
                ('alcohol_level', models.FloatField(default=-1)),
                ('blood_oxygen_level', models.FloatField(default=-1)),
                ('heartrate', models.IntegerField(default=-1)),
                ('num_records', models.IntegerField(default=0)),
                ('date_last_updated', models.DateTimeField(verbose_name='Date of last update')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat', models.IntegerField(default=-1)),
                ('blood_oxygen_level', models.FloatField(default=-1)),
                ('alcohol_level', models.FloatField(default=-1)),
                ('date_time_recording', models.DateTimeField(verbose_name='Time of data recording')),
                ('date_time_sent', models.DateTimeField(verbose_name='Time of data transmission')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ben12app.client')),
            ],
        ),
    ]
