# Generated by Django 4.2.1 on 2023-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben12app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_measurement',
            field=models.DateTimeField(blank=True, verbose_name='DateTime of last record'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_time_alcohol_consumed',
            field=models.DateTimeField(blank=True, verbose_name='Last alcohol consumption'),
        ),
    ]
