# Generated by Django 4.2.1 on 2023-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben12app', '0002_alter_client_last_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_measurement',
            field=models.DateTimeField(null=True, verbose_name='DateTime of last record'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_time_alcohol_consumed',
            field=models.DateTimeField(null=True, verbose_name='Last alcohol consumption'),
        ),
    ]
