# Generated by Django 4.2.2 on 2023-06-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben12app', '0003_alter_client_last_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='ben12app.client'),
        ),
    ]
