# Generated by Django 4.2.2 on 2023-06-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben12app', '0004_alter_record_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ben12app.client'),
        ),
        migrations.AlterField(
            model_name='record',
            name='heartbeat',
            field=models.FloatField(default=-1),
        ),
    ]
