# Generated by Django 4.2.2 on 2023-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben12app', '0005_alter_record_client_alter_record_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='should_test_alcohol',
            field=models.BooleanField(default=False),
        ),
    ]
